
  language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/movies;

node_js:
  - 12
before_script:
  - psql -c 'create database movies' -U postgres
  - psql -U postgres -d movies -a -f ../server/sql/movie_user.sql
services:
  - postgresql
 script: run test.js


